name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Batty better? Describe the problem you're trying to solve.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? Why is it needed?
      placeholder: "When running parallel agents, I need to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?

  - type: dropdown
    id: scope
    attributes:
      label: Area
      description: Which part of Batty does this affect?
      options:
        - CLI / UX
        - Supervisor / Prompt Detection
        - Scheduler / Parallel Execution
        - Merge Queue
        - Kanban / Task Management
        - Configuration
        - Documentation
        - Other

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Anything else? Screenshots, log snippets, related issues.
