#!/usr/bin/env bash
set -euo pipefail

echo "=== Batty + clawhip Discord Setup ==="
echo ""
echo "This script configures clawhip to route batty development events to Discord."
echo ""

# Check clawhip is installed
if ! command -v clawhip &>/dev/null; then
    echo "ERROR: clawhip not found. Install with:"
    echo "  curl --proto '=https' --tlsv1.2 -LsSf https://github.com/Yeachan-Heo/clawhip/releases/latest/download/clawhip-installer.sh | sh"
    exit 1
fi

echo "clawhip $(clawhip --version 2>&1 | head -1) found."
echo ""

# Get Discord bot token
if [ -n "${DISCORD_TOKEN:-}" ]; then
    echo "Using DISCORD_TOKEN from environment."
    BOT_TOKEN="$DISCORD_TOKEN"
else
    echo "Enter your Discord bot token (from https://discord.com/developers/applications):"
    read -rsp "Bot token: " BOT_TOKEN
    echo ""
fi

if [ -z "$BOT_TOKEN" ]; then
    echo "ERROR: Bot token cannot be empty."
    exit 1
fi

# Get channel IDs
echo ""
echo "Enter Discord channel IDs (right-click channel → Copy Channel ID):"
echo ""

read -rp "Events channel ID (#batty-events): " EVENTS_CHANNEL
read -rp "Agents channel ID (#batty-agents): " AGENTS_CHANNEL
read -rp "Commands channel ID (#batty-commands, or press Enter to use events channel): " COMMANDS_CHANNEL

COMMANDS_CHANNEL="${COMMANDS_CHANNEL:-$EVENTS_CHANNEL}"

# Write config
mkdir -p ~/.clawhip

cat > ~/.clawhip/config.toml << EOF
# clawhip config for batty development — generated by setup-discord-clawhip.sh
# $(date -u +%Y-%m-%dT%H:%M:%SZ)

[providers.discord]
token = "$BOT_TOKEN"
default_channel = "$EVENTS_CHANNEL"

[dispatch]
routine_batch_window_secs = 5
ci_batch_window_secs = 30

[defaults]
channel = "$EVENTS_CHANNEL"

# Git commit events → #batty-events
[[routes]]
event = "git.commit"
filter = { repo = "batty" }
sink = "discord"
channel = "$EVENTS_CHANNEL"
format = "compact"

# OMX session events → #batty-agents
[[routes]]
event = "session.*"
filter = { tool = "omx", repo_name = "batty" }
sink = "discord"
channel = "$AGENTS_CHANNEL"
format = "compact"

# Agent lifecycle events → #batty-agents
[[routes]]
event = "agent.*"
filter = { project = "batty" }
sink = "discord"
channel = "$AGENTS_CHANNEL"
format = "alert"

# Test events → #batty-events
[[routes]]
event = "session.test-*"
filter = { tool = "omx" }
sink = "discord"
channel = "$EVENTS_CHANNEL"
format = "compact"

# Blocked/failed events → #batty-commands (for human attention)
[[routes]]
event = "session.blocked"
filter = { tool = "omx" }
sink = "discord"
channel = "$COMMANDS_CHANNEL"
format = "alert"

[[routes]]
event = "session.failed"
filter = { tool = "omx" }
sink = "discord"
channel = "$COMMANDS_CHANNEL"
format = "alert"
EOF

echo ""
echo "Config written to ~/.clawhip/config.toml"
echo ""

# Start the daemon
echo "Starting clawhip daemon..."
clawhip &
CLAWHIP_PID=$!
sleep 2

# Health check
if clawhip status &>/dev/null; then
    echo "clawhip daemon is running (PID $CLAWHIP_PID)"
    echo ""

    # Test by sending a message
    echo "Sending test message to Discord..."
    clawhip send --channel "$EVENTS_CHANNEL" --message "🦇 clawhip connected to batty development. Events will appear here." 2>&1 || echo "  (send failed — check bot permissions)"
    echo ""
    echo "=== Setup complete! ==="
    echo ""
    echo "Next steps:"
    echo "  1. Check your Discord #batty-events channel for the test message"
    echo "  2. Run: cd ~/batty && omx team 3:executor 'work through the batty kanban board tasks tagged orchestration-loop'"
    echo "  3. Or for a single task: cd ~/batty && codex  # then type: \$ralph 'implement task #514'"
    echo ""
    echo "clawhip is running in the background. To stop: kill $CLAWHIP_PID"
    echo "To restart later: clawhip &"
else
    echo "WARNING: clawhip daemon may not have started correctly."
    echo "Check: clawhip status"
    echo "Logs: check stderr output above"
fi
